unit ClassPreencheDataSet;

interface

uses
  Datasnap.DBClient, System.SysUtils, System.Variants, System.Classes, Data.DB;

type
  TNF = class
  private
    FDataSetGrupo: TClientDataSet;
    FDataSetGridNF: TClientDataSet;
    FDataSetProduto: TClientDataSet;
    FDataSetFornecedor: TClientDataSet;
  private
    procedure SetDataSetNF();
    procedure CreateDataSetNF();
    procedure SetDataSetGrupo();
    procedure SetDataSetProduto();
    procedure CreateDataSetGrupo();
    procedure CreateDataSetProduto();
    procedure SetDataSetFornecedor();
    procedure CreateDataSetForncedor();
    procedure PreencheDataSetGrupo(const pNome: String);
    procedure PreencheDataSetFornecedor(const pNome: String);
    procedure PreencheDataSetProduto(const pNome, pUnd, pGrupo, pFornecedor: String; pPreco: Double);
    procedure PreencheDataSetNF(const pMes, pSemana: string; pDia: Integer; pGrupo, pFornecedor, pProduto, pUnidade: String; pQtd, pPreco, pVlTotal: Double; pNF: Integer);
  public
    function GetDataSetNF(): TClientDataSet;
    function GetDataSetGrupo(): TClientDataSet;
    function GetDataSetProduto(): TClientDataSet;
    function GetDataSetFornecedor(): TClientDataSet;
  public
    constructor Create;
  end;

implementation

{ TNF }

constructor TNF.Create;
begin
  FDataSetGrupo := TClientDataSet.Create(nil);
  FDataSetGridNF := TClientDataSet.Create(nil);
  FDataSetProduto := TClientDataSet.Create(nil);
  FDataSetFornecedor := TClientDataSet.Create(nil);

  CreateDataSetNF();
  CreateDataSetGrupo();
  CreateDataSetProduto();
  CreateDataSetForncedor();

  SetDataSetNF();
  SetDataSetGrupo();
  SetDataSetProduto();
  SetDataSetFornecedor();
end;

procedure TNF.CreateDataSetForncedor;
begin
  FDataSetFornecedor.FieldDefs.Add('Nome', ftString, 50);
  FDataSetFornecedor.CreateDataSet;
end;

procedure TNF.CreateDataSetGrupo;
begin
  FDataSetGrupo.FieldDefs.Add('Nome', ftString, 50);
  FDataSetGrupo.CreateDataSet;
end;

procedure TNF.CreateDataSetNF;
begin
  FDataSetGridNF.FieldDefs.Add('Mes', ftString, 20);
  FDataSetGridNF.FieldDefs.Add('Semana', ftString, 20);
  FDataSetGridNF.FieldDefs.Add('Dia', ftInteger, 0);
  FDataSetGridNF.FieldDefs.Add('Grupo', ftString, 50);
  FDataSetGridNF.FieldDefs.Add('Fornecedor', ftString, 50);
  FDataSetGridNF.FieldDefs.Add('Produto', ftString, 50);
  FDataSetGridNF.FieldDefs.Add('Und', ftString, 20);
  FDataSetGridNF.FieldDefs.Add('Qtd', ftFloat, 0);
  FDataSetGridNF.FieldDefs.Add('Preco', ftFloat, 0);
  FDataSetGridNF.FieldDefs.Add('VlTotal', ftFloat, 0);
  FDataSetGridNF.FieldDefs.Add('NF', ftInteger, 0);
  FDataSetGridNF.CreateDataSet();
end;

procedure TNF.CreateDataSetProduto;
begin
  FDataSetProduto.FieldDefs.Add('Nome', ftString, 50);
  FDataSetProduto.FieldDefs.Add('Unidade', ftString, 10);
  FDataSetProduto.FieldDefs.Add('Grupo', ftString, 50);
  FDataSetProduto.FieldDefs.Add('Fornecedor', ftString, 50);
  FDataSetProduto.FieldDefs.Add('Preco', ftFloat);
  FDataSetProduto.CreateDataSet;
end;

function TNF.GetDataSetFornecedor: TClientDataSet;
begin
  Result := FDataSetFornecedor;
end;

function TNF.GetDataSetGrupo: TClientDataSet;
begin
  Result := FDataSetGrupo;
end;

function TNF.GetDataSetNF: TClientDataSet;
begin
  Result := FDataSetGridNF;
end;

function TNF.GetDataSetProduto: TClientDataSet;
begin
  Result := FDataSetProduto;
end;

procedure TNF.PreencheDataSetFornecedor(const pNome: String);
begin
  FDataSetFornecedor.Append;
  FDataSetFornecedor.FieldByName('Nome').AsString := pNome;
  FDataSetFornecedor.Post;
end;

procedure TNF.PreencheDataSetGrupo(const pNome: String);
begin
  FDataSetGrupo.Append;
  FDataSetGrupo.FieldByName('Nome').AsString := pNome;
  FDataSetGrupo.Post;
end;

procedure TNF.PreencheDataSetNF(const pMes, pSemana: string; pDia: Integer; pGrupo, pFornecedor, pProduto, pUnidade: String;
  pQtd, pPreco, pVlTotal: Double; pNF: Integer);
begin
  FDataSetGridNF.Append;
  FDataSetGridNF.FieldByName('Mes').AsString := pMes;
  FDataSetGridNF.FieldByName('Semana').AsString := pSemana;
  FDataSetGridNF.FieldByName('Dia').AsInteger := pDia;
  FDataSetGridNF.FieldByName('Grupo').AsString := pGrupo;
  FDataSetGridNF.FieldByName('Fornecedor').AsString := pFornecedor;
  FDataSetGridNF.FieldByName('Produto').AsString := pProduto;
  FDataSetGridNF.FieldByName('Und').AsString := pUnidade;
  FDataSetGridNF.FieldByName('Qtd').AsFloat := pQtd;
  FDataSetGridNF.FieldByName('Preco').AsFloat := pPreco;
  FDataSetGridNF.FieldByName('VlTotal').AsFloat := pVlTotal;
  FDataSetGridNF.Post;
end;

procedure TNF.PreencheDataSetProduto(const pNome, pUnd, pGrupo, pFornecedor: String; pPreco: Double);
begin
  FDataSetProduto.Append;
  FDataSetProduto.FieldByName('Nome').AsString := pNome;
  FDataSetProduto.FieldByName('Unidade').AsString := pUnd;
  FDataSetProduto.FieldByName('Grupo').AsString := pGrupo;
  FDataSetProduto.FieldByName('Fornecedor').AsString := pFornecedor;
  FDataSetProduto.FieldByName('Preco').AsFloat := pPreco;
  FDataSetProduto.Post;
end;

procedure TNF.SetDataSetFornecedor();
begin
  PreencheDataSetFornecedor('Mercadinho Bambina');
  PreencheDataSetFornecedor('Planeta Gelo');
  PreencheDataSetFornecedor('Feira');
  PreencheDataSetFornecedor('Fernanda Alves');
  PreencheDataSetFornecedor('Sitio do Moinho');
  PreencheDataSetFornecedor('Laticinios Alhambra');
  PreencheDataSetFornecedor('Pescarimarcar');
  PreencheDataSetFornecedor('Barrinhas');
  PreencheDataSetFornecedor('Reginaves');
  PreencheDataSetFornecedor('Frigorifico Jahu');
  PreencheDataSetFornecedor('Alcibiades G. Quintas');
  PreencheDataSetFornecedor('Umehara');
  PreencheDataSetFornecedor('Super Mercado Zonasul');
  PreencheDataSetFornecedor('Nutry Max');
  PreencheDataSetFornecedor('Mar e Terra');
  PreencheDataSetFornecedor('Kolnex');
  PreencheDataSetFornecedor('Luisa');
  PreencheDataSetFornecedor('Rioaves');
  PreencheDataSetFornecedor('Piffer Torteria');
  PreencheDataSetFornecedor('Diana (Guloseima Saudavel)');
  PreencheDataSetFornecedor('Mamy');
  PreencheDataSetFornecedor('Top Alto');
  PreencheDataSetFornecedor('Rio Quality');
  PreencheDataSetFornecedor('J. Araujo (Arcofood)');
  PreencheDataSetFornecedor('Zamboni');
  PreencheDataSetFornecedor('CDI');
  PreencheDataSetFornecedor('Toca da Lagosta');
  PreencheDataSetFornecedor('Minalba');
  PreencheDataSetFornecedor('Italimp');
  PreencheDataSetFornecedor('Mundo Natural');
  PreencheDataSetFornecedor('Tempero Carioca');
  PreencheDataSetFornecedor('Nova Geração (Casa Pedro)');
  PreencheDataSetFornecedor('Sanda Produtos');
  PreencheDataSetFornecedor('Truticultura da Serra');
  PreencheDataSetFornecedor('Melhoramentos');
  PreencheDataSetFornecedor('Marfrig');
  PreencheDataSetFornecedor('Cheiro Verde');
  PreencheDataSetFornecedor('Central RJ');
  PreencheDataSetFornecedor('Frisa');
  PreencheDataSetFornecedor('Lenira Brandão (Suzanne)');
  PreencheDataSetFornecedor('Wah Sin');
  PreencheDataSetFornecedor('CRBS');
  PreencheDataSetFornecedor('Artesanal Produtos');
  PreencheDataSetFornecedor('Atelier dos Sabores');
  PreencheDataSetFornecedor('Mercearia Fuji');
  PreencheDataSetFornecedor('Batata, o Rei do Alho');
  PreencheDataSetFornecedor('Rio de Janeiro');
  PreencheDataSetFornecedor('DM Com. Pescados');
  PreencheDataSetFornecedor('Papelex');
  PreencheDataSetFornecedor('Ceni');
  PreencheDataSetFornecedor('LKAP');
  PreencheDataSetFornecedor('Ecolab');
  PreencheDataSetFornecedor('Estrela Real');
  PreencheDataSetFornecedor('Chez Bonbon');
  PreencheDataSetFornecedor('Agropart');
  PreencheDataSetFornecedor('M2HP');
  PreencheDataSetFornecedor('Nossos Sabores');
  PreencheDataSetFornecedor('Ind. Caseira de Doces Helena');
  PreencheDataSetFornecedor('Satiro');
  PreencheDataSetFornecedor('Bonduelle');
  PreencheDataSetFornecedor('Peixaria Só Peixe');
  PreencheDataSetFornecedor('Suprimix');
  PreencheDataSetFornecedor('Café Fazenta (Orfeu)');
  PreencheDataSetFornecedor('Casa Flora');
  PreencheDataSetFornecedor('Damy');
  PreencheDataSetFornecedor('Ding Show');
  PreencheDataSetFornecedor('Rio Pak');
  PreencheDataSetFornecedor('Aurora');
  PreencheDataSetFornecedor('Sanda');
  PreencheDataSetFornecedor('Horn (Arosa)');
  PreencheDataSetFornecedor('FNS');
  PreencheDataSetFornecedor('Cambuci');
  PreencheDataSetFornecedor('Fabene');
  PreencheDataSetFornecedor('Celpa Quimica');
  PreencheDataSetFornecedor('mamy');
end;

procedure TNF.SetDataSetGrupo();
begin
  PreencheDataSetGrupo('Mercado');
  PreencheDataSetGrupo('Hortifruti');
  PreencheDataSetGrupo('Descartável');
  PreencheDataSetGrupo('Carnes');
  PreencheDataSetGrupo('Sushi');
  PreencheDataSetGrupo('Sobremesa');
  PreencheDataSetGrupo('Feirinha');
  PreencheDataSetGrupo('Vendas Caixa');
  PreencheDataSetGrupo('Bebidas');
  PreencheDataSetGrupo('Limpeza');
  PreencheDataSetGrupo('Escritório');
end;

procedure TNF.SetDataSetNF();
begin
  PreencheDataSetNF('Outubro','SEMANA 1',1,'Mercado','Mercadinho Bambina','Pão Rabanada','unid',10,6.01,6.01,45328);
  PreencheDataSetNF('Outubro','SEMANA 1',1,'Mercado','Mercadinho Bambina','Pão Árabe','pcte',2,6.7,7.01,45328);
  PreencheDataSetNF('Outubro','SEMANA 1',1,'Mercado','Mercadinho Bambina','Batata Palha 140 g','pcte',2,7.8,8.01,45328);
  PreencheDataSetNF('Outubro','SEMANA 1',1,'Hortifruti','Mercadinho Bambina','Manjericão','kg',1,1,33,453);
  PreencheDataSetNF('Outubro','SEMANA 1',1,'Mercado','Planeta Gelo','Gelo em Escamas','saco',1,7.5,3.4,9729);
  PreencheDataSetNF('Outubro','SEMANA 1',1,'Mercado','Planeta Gelo','Gelo em Cubo','saco',2,7.5,3.5,9729);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Mercado','Planeta Gelo','Gelo em Escamas','saco',1,7.5,3.6,9872);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Mercado','Planeta Gelo','Gelo em Cubo','saco',3,7.5,3.7,9872);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Mercado','Mercadinho Bambina','Pão Francês','kg',0,185,13.98,9873);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Mercado','Feira','Massa de Pastel','kg',28,2,7.4468085106383,9874);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Feira','Acelga','kg',1,5,4,9875);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Feira','Aipim','kg',20,5,100,9876);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Descartável','Fernanda Alves','Sacola Delivery','unid',5010,0.77,101,2020);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Sitio do Moinho','Alface Americana Orgânica','kg',11,44,6.33741258741259,82576);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Sitio do Moinho','Alface crespa Orgânica','kg',3,84,103,82576);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Sitio do Moinho','Alface Roxa Orgânica','kg',1,44,10.4166666666667,82576);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Sitio do Moinho','Beterraba Orgânica','kg',3,7.7,105,82576);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Sitio do Moinho','Cenoura Orgânica','kg',6,7.75,106,82576);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Sitio do Moinho','Rúcula Orgânica','kg',3,21.3333333333333,107,82576);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Mercado','Laticinios Alhambra','Creme de Leite Culinário 20% Bd 10 Lt','bd',1,142.45,108,810306);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Mercado','Laticinios Alhambra','Queijo Mussarela','kg',3,5,26,810306);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Mercado','Laticinios Alhambra','Queijo Minas','kg',4,6,20.8,810306);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Carnes','Pescarimarcar','Pescados - Filé Linguado Cong. G','kg',30,42,1260,280682);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Carnes','Pescarimarcar','Pescados - Lula Calamares','kg',10,28,280,280682);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Carnes','Barrinhas','Pescados - Bacalhau Salgado','kg',25,43.9216,281,153234);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Carnes','Reginaves','Aves - Filé de Peito de Frango','kg',48,7.8,282,3267635);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Sushi','Frigorifico Jahu','Pescados - Salmão Inteiro Sushi','kg',22,05,27.9002,1229181);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Alcibiades G. Quintas','Batata Doce','kg',17,94,1.67224080267559,1768);
  PreencheDataSetNF('Outubro','SEMANA 1',2,'Hortifruti','Alcibiades G. Quintas','Pimentão Verde','kg',1,4,4,1768);
end;

procedure TNF.SetDataSetProduto();
begin
  PreencheDataSetProduto('Pão Rabanada','unid','Mercado','Mercadinho Bambina',6.01);
  PreencheDataSetProduto('Pão Árabe','pcte','Mercado','Mercadinho Bambina',6.7);
  PreencheDataSetProduto('Batata Palha 140 g','pcte','Mercado','Mercadinho Bambina',7.8);
  PreencheDataSetProduto('Manjericão','kg','Hortifruti','Mercadinho Bambina',33);
  PreencheDataSetProduto('Gelo em Escamas','saco','Mercado','Planeta Gelo',7.5);
  PreencheDataSetProduto('Gelo em Cubo','saco','Mercado','Planeta Gelo',7.5);
  PreencheDataSetProduto('Pão Francês','kg','Mercado','Mercadinho Bambina',13.98);
  PreencheDataSetProduto('Massa de Pastel','kg','Mercado','Feira',7.4468085106383);
  PreencheDataSetProduto('Acelga','kg','Hortifruti','Feira',4);
  PreencheDataSetProduto('Aipim','kg','Hortifruti','Feira',5);
  PreencheDataSetProduto('Sacola Delivery','unid','Descartável','Fernanda Alves',0.77);
  PreencheDataSetProduto('Alface Americana Orgânica','kg','Hortifruti','Sitio do Moinho',6.33741258741259);
  PreencheDataSetProduto('Alface crespa Orgânica','kg','Hortifruti','Sitio do Moinho',6.51041666666667);
  PreencheDataSetProduto('Alface Roxa Orgânica','kg','Hortifruti','Sitio do Moinho',10.4166666666667);
  PreencheDataSetProduto('Beterraba Orgânica','kg','Hortifruti','Sitio do Moinho',7.7);
  PreencheDataSetProduto('Cenoura Orgânica','kg','Hortifruti','Sitio do Moinho',7.75);
  PreencheDataSetProduto('Rúcula Orgânica','kg','Hortifruti','Sitio do Moinho',21.3333333333333);
  PreencheDataSetProduto('Creme de Leite Culinário 20% Bd 10 Lt','bd','Mercado','Laticinios Alhambra',142.45);
  PreencheDataSetProduto('Queijo Mussarela','kg','Mercado','Laticinios Alhambra',26);
  PreencheDataSetProduto('Queijo Minas','kg','Mercado','Laticinios Alhambra',20.8);
  PreencheDataSetProduto('Pescados - Filé Linguado Cong. G','kg','Carnes','Pescarimarcar',42);
  PreencheDataSetProduto('Pescados - Lula Calamares','kg','Carnes','Pescarimarcar',28);
  PreencheDataSetProduto('Pescados - Bacalhau Salgado','kg','Carnes','Barrinhas',43.9216);
  PreencheDataSetProduto('Aves - Filé de Peito de Frango','kg','Carnes','Reginaves',7.8);
  PreencheDataSetProduto('Pescados - Salmão Inteiro Sushi','kg','Sushi','Frigorifico Jahu',27.9002);
  PreencheDataSetProduto('Batata Doce','kg','Hortifruti','Alcibiades G. Quintas',1.67224080267559);
  PreencheDataSetProduto('Pimentão Verde','kg','Hortifruti','Alcibiades G. Quintas',4);
  PreencheDataSetProduto('Pimentão Amarelo','kg','Hortifruti','Alcibiades G. Quintas',8);
  PreencheDataSetProduto('Pimentão Vermelho','kg','Hortifruti','Alcibiades G. Quintas',8);
  PreencheDataSetProduto('Tomate Salada','kg','Hortifruti','Alcibiades G. Quintas',2.0891364902507);
  PreencheDataSetProduto('Alho Poró ','kg','Hortifruti','Alcibiades G. Quintas',8);
  PreencheDataSetProduto('Brócolis Americano','kg','Hortifruti','Alcibiades G. Quintas',7);
  PreencheDataSetProduto('Banana DÁgua','kg','Hortifruti','Alcibiades G. Quintas',3.4);
  PreencheDataSetProduto('Limão','kg','Hortifruti','Alcibiades G. Quintas',5.49450549450549);
  PreencheDataSetProduto('Manga Palmer','kg','Hortifruti','Alcibiades G. Quintas',5.45454545454545);
  PreencheDataSetProduto('Pera','kg','Hortifruti','Alcibiades G. Quintas',8);
  PreencheDataSetProduto('Batata HBT','kg','Hortifruti','Umehara',1.25);
  PreencheDataSetProduto('Cebola','kg','Hortifruti','Umehara',1.28516003879728);
  PreencheDataSetProduto('Cebolinha Verde','kg','Hortifruti','Umehara',7.5);
  PreencheDataSetProduto('Côco Verde','unid','Hortifruti','Umehara',1.8);
  PreencheDataSetProduto('Goiaba','kg','Hortifruti','Umehara',6);
  PreencheDataSetProduto('Mamão Bahia','kg','Hortifruti','Umehara',3.5);
  PreencheDataSetProduto('Melão de Rede ','kg','Hortifruti','Umehara',5.9);
  PreencheDataSetProduto('Salsa','kg','Hortifruti','Umehara',7.5);
  PreencheDataSetProduto('Abacaxi ','kg','Hortifruti','Umehara',2.5);
  PreencheDataSetProduto('Endivia','kg','Hortifruti','Umehara',19.9);
  PreencheDataSetProduto('Espinafre','kg','Hortifruti','Umehara',5.9);
  PreencheDataSetProduto('Laranja Pera','kg','Hortifruti','Umehara',1.26050420168067);
  PreencheDataSetProduto('Melância','kg','Hortifruti','Umehara',1.59);
  PreencheDataSetProduto('Couve Flor','kg','Hortifruti','Umehara',4.25);
  PreencheDataSetProduto('Maçã Nacional','kg','Hortifruti','Umehara',3.22);
  PreencheDataSetProduto('Côco Seco','kg','Mercado','Super Mercado Zonasul',8.99);
  PreencheDataSetProduto('Pão de Forma','pcte','Mercado','Mercadinho Bambina',3935);
  PreencheDataSetProduto('Gelatina em pó s/ sabor (incolor)','pcte','Mercado','Mercadinho Bambina',5.45);
  PreencheDataSetProduto('Tapioca Granulada ','kg','Mercado','Mercadinho Bambina',11);
  PreencheDataSetProduto('Chá diversos sache','pcte','Mercado','Mercadinho Bambina',5.98);
  PreencheDataSetProduto('Goiabada','unid','Mercado','Mercadinho Bambina',7.98);
  PreencheDataSetProduto('Yogurt de Pessego','unid','Mercado','Mercadinho Bambina',6.98);
  PreencheDataSetProduto('Aves - Sobrecoxa','kg','Carnes','Nutry Max',5.35);
  PreencheDataSetProduto('Carne Bovina - Carne Seca','kg','Carnes','Nutry Max',16.19);
  PreencheDataSetProduto('Carne Bovina - Peito','kg','Carnes','Nutry Max',10.99);
  PreencheDataSetProduto('Suíno - Linguiça Calabresa','kg','Carnes','Nutry Max',9.49);
  PreencheDataSetProduto('Carne Bovina - Bucho','kg','Carnes','Nutry Max',8.99);
  PreencheDataSetProduto('Abobora','kg','Hortifruti','Umehara',2.2);
  PreencheDataSetProduto('Batata Calabresa','kg','Hortifruti','Umehara',1.75);
  PreencheDataSetProduto('Berinjela','kg','Hortifruti','Umehara',2.97927461139896);
  PreencheDataSetProduto('Chicória','kg','Hortifruti','Umehara',3.5);
  PreencheDataSetProduto('Hortelã','kg','Hortifruti','Umehara',4.5);
  PreencheDataSetProduto('Inhame','kg','Hortifruti','Umehara',2.1);
  PreencheDataSetProduto('Manga Tommy','kg','Hortifruti','Umehara',2.2);
  PreencheDataSetProduto('Tomate Cereja','kg','Hortifruti','Umehara',2.3);
  PreencheDataSetProduto('Vagem Macarrão','kg','Hortifruti','Umehara',2.4);
  PreencheDataSetProduto('Cenoura','kg','Hortifruti','Alcibiades G. Quintas',1.86965811965812);
  PreencheDataSetProduto('Chuchu','kg','Hortifruti','Alcibiades G. Quintas',1.68350168350168);
  PreencheDataSetProduto('Cebola Calabresa','kg','Hortifruti','Alcibiades G. Quintas',4);
  PreencheDataSetProduto('Cará','kg','Hortifruti','Alcibiades G. Quintas',6.8);
  PreencheDataSetProduto('Alfafa','kg','Hortifruti','Alcibiades G. Quintas',40);
  PreencheDataSetProduto('Tofu Kilo','kg','Hortifruti','Alcibiades G. Quintas',14);
  PreencheDataSetProduto('Abacate Sushi','kg','Sushi','Alcibiades G. Quintas',6.8);
  PreencheDataSetProduto('Kiwi','kg','Hortifruti','Alcibiades G. Quintas',14);
  PreencheDataSetProduto('Pescados - Filé Tilápia Cong.','kg','Carnes','Mar e Terra',26.3);
  PreencheDataSetProduto('Saco Plástico 50x70','pcte','Descartável','Kolnex',49.85);
  PreencheDataSetProduto('Clara de Ovo','kg','Mercado','Luisa',6.46830530401035);
  PreencheDataSetProduto('Ovo de Codorna','pce','Hortifruti','Rioaves',10.4);
  PreencheDataSetProduto('Torta Xcake Framboesa','fatia','Sobremesa','Piffer Torteria',6.16666666666667);
  PreencheDataSetProduto('Geléia de Framboesa','unid','Sobremesa','Piffer Torteria',6.1);
  PreencheDataSetProduto('Pão de Psylium c/Quinoa','pcte','Feirinha','Diana (Guloseima Saudavel)',11.2);
  PreencheDataSetProduto('Bala de Alga 500 g','pcte','Vendas Caixa','Mamy',17.16);
  PreencheDataSetProduto('Farinha Panco','kg','Mercado','Mamy',17.7);
  PreencheDataSetProduto('Gergelim Branco','kg','Mercado','Mamy',16.85);
  PreencheDataSetProduto('Massa de Harumaki','folha','Mercado','Mamy',0.575833333333333);
  PreencheDataSetProduto('Suíno - Costelinha Salgada','kg','Carnes','Nutry Max',9.98);
  PreencheDataSetProduto('Suíno - Linguiça de Pernil','kg','Carnes','Nutry Max',10.05);
  PreencheDataSetProduto('Suíno - Bacon','kg','Carnes','Nutry Max',13.24);
  PreencheDataSetProduto('Suíno - Pernil s/ Osso','kg','Carnes','Nutry Max',8.89);
  PreencheDataSetProduto('Pescados - Camarão IQF Evisc. 51/60','kg','Carnes','Pescarimarcar',45);
  PreencheDataSetProduto('Suíno - Lombo Salgado','kg','Carnes','Top Alto',10.45);
  PreencheDataSetProduto('Carne Bovina - Alcatra Miolo','kg','Carnes','Top Alto',21.98);
  PreencheDataSetProduto('Queijo Coalho','kg','Mercado','Top Alto',24.13);
  PreencheDataSetProduto('Leite de Côco','lt','Mercado','Rio Quality',15.11);
  PreencheDataSetProduto('Leite Condensado 395 g','unid','Mercado','Rio Quality',6.64208333333333);
  PreencheDataSetProduto('Leite Integral','lt','Mercado','Rio Quality',2.88902777777778);
  PreencheDataSetProduto('Óleo de Soja 18 Lt','bag','Mercado','Rio Quality',61.98);
  PreencheDataSetProduto('Feijão Branco','kg','Mercado','Rio Quality',7.3);
  PreencheDataSetProduto('Fermento em Pó Royal 250 g','unid','Mercado','Rio Quality',6.9);
  PreencheDataSetProduto('Macarrão Espaghetti Nissim','kg','Mercado','Rio Quality',10.24);
  PreencheDataSetProduto('Trigo para Kibe','kg','Mercado','Rio Quality',3.39);
  PreencheDataSetProduto('Feijão Preto','kg','Mercado','J. Araujo (Arcofood)',4506);
  PreencheDataSetProduto('Farinha de Mandioca','kg','Mercado','J. Araujo (Arcofood)',4.1305);
  PreencheDataSetProduto('Sal Refinado','kg','Mercado','J. Araujo (Arcofood)',0.8);
  PreencheDataSetProduto('Nescau (Nestle)','kg','Mercado','J. Araujo (Arcofood)',17.62);
  PreencheDataSetProduto('Vinagre Aceto Balsamico','unid','Mercado','Zamboni',9.02);
  PreencheDataSetProduto('Café Moído 1 Kg','kg','Mercado','Zamboni',16.12);
  PreencheDataSetProduto('Vinagre de Arroz Sushi','lt','Sushi','Zamboni',5.28);
  PreencheDataSetProduto('Maionese Hellmanns Bd 3 Kg','bd','Mercado','Zamboni',21.52);
  PreencheDataSetProduto('Margarina Bd 15 Kg','bd','Mercado','Zamboni',74.35);
  PreencheDataSetProduto('Shoyu Light Bb 5 Lt','bb','Mercado','Zamboni',59.88);
  PreencheDataSetProduto('Shoyu Tradicional (Sushi) Bb 5 Lt','bb','Sushi','Zamboni',47.25);
  PreencheDataSetProduto('Tonkatsu Bb 5 Lt','bb','Mercado','Zamboni',62.54);
  PreencheDataSetProduto('Mostarda Bb 3,3, Kg','bb','Mercado','Zamboni',11.16);
  PreencheDataSetProduto('Açucar Refinado','kg','Mercado','CDI',2234);
  PreencheDataSetProduto('Arroz Branco','kg','Mercado','CDI',3292);
  PreencheDataSetProduto('Feijão Mulatinho','kg','Mercado','CDI',11.46);
  PreencheDataSetProduto('Farinha de Trigo','kg','Mercado','CDI',1622);
  PreencheDataSetProduto('Karo Mel','unid','Mercado','CDI',6.43333333333333);
  PreencheDataSetProduto('Grão de Bico','kg','Mercado','CDI',14.84);
  PreencheDataSetProduto('Batata Baroa','kg','Hortifruti','Umehara',4.4);
  PreencheDataSetProduto('Couve Manteiga','kg','Hortifruti','Umehara',3);
  PreencheDataSetProduto('Limão Siciliano','kg','Hortifruti','Umehara',6.66);
  PreencheDataSetProduto('Manga Tommy Sushi','kg','Sushi','Umehara',3.5);
  PreencheDataSetProduto('Batata Yacon','kg','Hortifruti','Alcibiades G. Quintas',8);
  PreencheDataSetProduto('Gengibre Sushi','kg','Sushi','Alcibiades G. Quintas',7.79727095516569);
  PreencheDataSetProduto('Aipo','kg','Hortifruti','Alcibiades G. Quintas',4);
  PreencheDataSetProduto('Coentro','kg','Hortifruti','Alcibiades G. Quintas',14);
  PreencheDataSetProduto('Tomilho','kg','Hortifruti','Alcibiades G. Quintas',30);
  PreencheDataSetProduto('Broto de Feijão','kg','Hortifruti','Alcibiades G. Quintas',14);
  PreencheDataSetProduto('Pescados - Atum Fresco Sushi','kg','Sushi','Toca da Lagosta',14.9);
  PreencheDataSetProduto('Pescados - Salmão Inteiro','kg','Carnes','Frigorifico Jahu',25.8999);
  PreencheDataSetProduto('Queijo Ricota','kg','Mercado','Laticinios Alhambra',10.6);
  PreencheDataSetProduto('Queijo Minas Padrão','kg','Mercado','Laticinios Alhambra',41.6);
  PreencheDataSetProduto('Água Mineral com Gás','unid','Bebidas','Minalba',1.25395833333333);
  PreencheDataSetProduto('Água Mineral sem Gás','unid','Bebidas','Minalba',1254);
  PreencheDataSetProduto('Álcool 70','unid','Limpeza','Italimp',4.9);
  PreencheDataSetProduto('Bobina Picotada 25X35','unid','Descartável','Italimp',9.42);
  PreencheDataSetProduto('Hipoclorito de Sódio Bb 5 Lt','bb','Limpeza','Italimp',17.75);
  PreencheDataSetProduto('Luva Descartável c/ 100','pcte','Descartável','Italimp',1.68);
  PreencheDataSetProduto('Papel Higiênico Rolo','unid','Descartável','Italimp',0.99375);
  PreencheDataSetProduto('Saco de Lixo 100 Lt','pcte','Limpeza','Italimp',36.6);
  PreencheDataSetProduto('Gelatina Morango Stevia Plus Zero 10 g','unid','Mercado','Mundo Natural',1.65);
  PreencheDataSetProduto('Açafrão','kg','Mercado','Tempero Carioca',11.9);
  PreencheDataSetProduto('Açucar Mascavo','kg','Mercado','Tempero Carioca',7.9);
  PreencheDataSetProduto('Castanha de Caju Picada','kg','Mercado','Tempero Carioca',44.9);
  PreencheDataSetProduto('Cevadinha','kg','Mercado','Tempero Carioca',5.9);
  PreencheDataSetProduto('Chimichurri','kg','Mercado','Tempero Carioca',26.5);
  PreencheDataSetProduto('Coloral','kg','Mercado','Tempero Carioca',5.5);
  PreencheDataSetProduto('Feijão Azuki','kg','Mercado','Tempero Carioca',11.5);
  PreencheDataSetProduto('Feijão de Soja','kg','Mercado','Tempero Carioca',5.7);
  PreencheDataSetProduto('Nozes sem casca','kg','Mercado','Tempero Carioca',63);
  PreencheDataSetProduto('Quinoa','kg','Mercado','Tempero Carioca',23.9);
  PreencheDataSetProduto('Trigo em Grão','kg','Mercado','Tempero Carioca',3.9);
  PreencheDataSetProduto('Tahine Lata 500 gr','unid','Mercado','Tempero Carioca',18.95);
  PreencheDataSetProduto('Passas Preta','kg','Mercado','Tempero Carioca',13.5);
  PreencheDataSetProduto('Arroz Integral Curto','kg','Mercado','Nova Geração (Casa Pedro)',8.4201);
  PreencheDataSetProduto('Tapioca Fina','kg','Mercado','Nova Geração (Casa Pedro)',8499);
  PreencheDataSetProduto('Bobina Picotada 40X50','unid','Descartável','Sanda Produtos',19.38);
  PreencheDataSetProduto('Esponja Dupla Face','unid','Limpeza','Sanda Produtos',1.25);
  PreencheDataSetProduto('Fibraço','unid','Limpeza','Sanda Produtos',1.64);
  PreencheDataSetProduto('Filme PVC 380 x 300m','unid','Descartável','Sanda Produtos',23.17);
  PreencheDataSetProduto('Filme PVC 380 x 1000 Sushi','unid','Sushi','Sanda Produtos',36.78);
  PreencheDataSetProduto('Inseticida','unid','Limpeza','Sanda Produtos',10.74);
  PreencheDataSetProduto('Luva de Borraca Forrada','unid','Descartável','Sanda Produtos',4.9);
  PreencheDataSetProduto('Saco de Lixo 20 Lt','pcte','Limpeza','Sanda Produtos',8.4);
  PreencheDataSetProduto('Saco de Lixo 200 Lt','pcte','Limpeza','Sanda Produtos',48.19);
  PreencheDataSetProduto('Luva Cano Longo','unid','Descartável','Sanda Produtos',17.05);
  PreencheDataSetProduto('Suíno - Costelinha Fresca','kg','Carnes','Top Alto',15.74);
  PreencheDataSetProduto('Suíno - Linguiça Paio','kg','Carnes','Top Alto',9.48);
  PreencheDataSetProduto('Queijo Parmezon','kg','Mercado','Top Alto',23.96);
  PreencheDataSetProduto('Pescados - Filé Truta Cong.','kg','Carnes','Truticultura da Serra',26);
  PreencheDataSetProduto('Cogumelo Paris','kg','Mercado','Truticultura da Serra',15.5);
  PreencheDataSetProduto('Guardanapo Pequeno','unid','Descartável','Melhoramentos',1.77661458333333);
  PreencheDataSetProduto('T.P. Interfolhado Melpaper','unid','Descartável','Melhoramentos',11205);
  PreencheDataSetProduto('Carne Bovina - Contra-filé (Chorizo)','kg','Carnes','Marfrig',24.6122);
  PreencheDataSetProduto('Azeite Extra Virgem (Santiago) 500 ml','unid','Mercado','Zamboni',16.3494444444444);
  PreencheDataSetProduto('Brócolis Nacional','kg','Hortifruti','Umehara',3.5);
  PreencheDataSetProduto('Pepino Japonês','kg','Hortifruti','Umehara',3.43878954607978);
  PreencheDataSetProduto('Salsa Crespa','kg','Hortifruti','Umehara',12.5);
  PreencheDataSetProduto('Abobora Japonesa','kg','Hortifruti','Cheiro Verde',2.51);
  PreencheDataSetProduto('Bertalha','kg','Hortifruti','Cheiro Verde',2.52);
  PreencheDataSetProduto('Ovos Extra','unid','Hortifruti','Cheiro Verde',0.319444444444444);
  PreencheDataSetProduto('Toalha Bobina','unid','Descartável','Central RJ',12);
  PreencheDataSetProduto('Abobrinha Org. Feirinha','kg','Feirinha','Sitio do Moinho',7.85);
  PreencheDataSetProduto('Alface Americana Org. Feirinha','kg','Feirinha','Sitio do Moinho',8.61629881154499);
  PreencheDataSetProduto('Alface Crespa Org. Feirinha','kg','Feirinha','Sitio do Moinho',8.17757009345794);
  PreencheDataSetProduto('Alface Roxa Org. Feirinha','kg','Feirinha','Sitio do Moinho',10.0931677018634);
  PreencheDataSetProduto('Banana Prata Org. Feirinha','kg','Feirinha','Sitio do Moinho',6.55);
  PreencheDataSetProduto('Berinjela Org. Feirinha','kg','Feirinha','Sitio do Moinho',8.2);
  PreencheDataSetProduto('Beterraba Orgânica Feirinha','kg','Feirinha','Sitio do Moinho',7.7);
  PreencheDataSetProduto('Cenoura Org. Feirinha','kg','Feirinha','Sitio do Moinho',7.75);
  PreencheDataSetProduto('Chuchu Org. Feirinha','kg','Feirinha','Sitio do Moinho',7.76);
  PreencheDataSetProduto('Couve Orgânica Feirinha','kg','Feirinha','Sitio do Moinho',9.33333333333333);
  PreencheDataSetProduto('Pepino Japonês Org. Feirinha','kg','Feirinha','Sitio do Moinho',14);
  PreencheDataSetProduto('Rucula Org. Feirinha','kg','Feirinha','Sitio do Moinho',21.3333333333333);
  PreencheDataSetProduto('Palitos de Dente (cx 500)','unid','Descartável','Mercadinho Bambina',1.1);
  PreencheDataSetProduto('Carne Bovina - Picanha Grill/Churrascaria','kg','Carnes','Frisa',36);
  PreencheDataSetProduto('Carne Bovina - Filé Mignon 3/4','kg','Carnes','Frisa',32);
  PreencheDataSetProduto('Queijo Requeijão BD 3,6 Kg','bd','Mercado','Laticinios Alhambra',74.4);
  PreencheDataSetProduto('Bolo de Cacau Belga','unid','Feirinha','Lenira Brandão (Suzanne)',9.5);
  PreencheDataSetProduto('Bolo de Banana (com Amendoas)','unid','Feirinha','Lenira Brandão (Suzanne)',9.5);
  PreencheDataSetProduto('Bolo de Cenoura (com cobertura de chocolate)','unid','Feirinha','Lenira Brandão (Suzanne)',9.5);
  PreencheDataSetProduto('Bolo de Fuba (com cobertura de goiaba)','unid','Feirinha','Lenira Brandão (Suzanne)',9.5);
  PreencheDataSetProduto('Mini Bolo de Cacau Belga','unid','Feirinha','Lenira Brandão (Suzanne)',4.5);
  PreencheDataSetProduto('Mini Bolo de Banana (com amendoas)','unid','Feirinha','Lenira Brandão (Suzanne)',4.5);
  PreencheDataSetProduto('Mini Bolo de Cenoura (com cobertura de chocolate)','unid','Feirinha','Lenira Brandão (Suzanne)',4.5);
  PreencheDataSetProduto('Mini Bolo de Fuba (com cobertura goiaba)','unid','Feirinha','Lenira Brandão (Suzanne)',4.5);
  PreencheDataSetProduto('Petit Four de Cacau Belga','unid','Feirinha','Lenira Brandão (Suzanne)',9.5);
  PreencheDataSetProduto('Petit Four de Queijo','unid','Feirinha','Lenira Brandão (Suzanne)',9.5);
  PreencheDataSetProduto('Petit Four de Amendoas','unid','Feirinha','Lenira Brandão (Suzanne)',9.5);
  PreencheDataSetProduto('Abobrinha ','kg','Hortifruti','Cheiro Verde',1.21753246753247);
  PreencheDataSetProduto('Cebola Roxa','kg','Hortifruti','Cheiro Verde',3.63);
  PreencheDataSetProduto('Nabo Japonês Sushi','kg','Sushi','Cheiro Verde',5);
  PreencheDataSetProduto('Óleo Composto 500ml','unid','Mercado','Rio Quality',3.48166666666667);
  PreencheDataSetProduto('Touca Branca','pcte','Descartável','Rio Quality',7.9);
  PreencheDataSetProduto('Folha de Alga 50F','pcte','Sushi','Wah Sin',33);
  PreencheDataSetProduto('Ice Tea Limão','unid','Bebidas','CRBS',1.95875);
  PreencheDataSetProduto('Água Tonica','unid','Bebidas','CRBS',1.86083333333333);
  PreencheDataSetProduto('Guaraná Antarctica Zero (lata)','unid','Bebidas','CRBS',1.33725);
  PreencheDataSetProduto('Guaraná Antarctica (lata)','unid','Bebidas','CRBS',1.3375);
  PreencheDataSetProduto('H2O Limão','unid','Bebidas','CRBS',2.14375);
  PreencheDataSetProduto('Cerveja Bohemia Long Neck 355 ml','unid','Bebidas','CRBS',2.65708333333333);
  PreencheDataSetProduto('Torta de Maça Integral','fatia','Sobremesa','Artesanal Produtos',4.9);
  PreencheDataSetProduto('Torta Bem Casado de Damasco','fatia','Sobremesa','Atelier dos Sabores',5.74291666666667);
  PreencheDataSetProduto('Torta de Brigadeiro c/ Raspas','fatia','Sobremesa','Atelier dos Sabores',5.56583333333333);
  PreencheDataSetProduto('Torta de Limão','fatia','Sobremesa','Atelier dos Sabores',5.30083333333333);
  PreencheDataSetProduto('Torta Bem Casado de Chocolate c/ Avelã','fatia','Sobremesa','Atelier dos Sabores',5.74291666666667);
  PreencheDataSetProduto('Flocos de Milho','kg','Mercado','Mercadinho Bambina',21);
  PreencheDataSetProduto('Vinagre de Arroz (cozinha)','lt','Mercado','Zamboni',5.28);
  PreencheDataSetProduto('Cenoura  Sushi','kg','Sushi','Cheiro Verde',1.86965811965812);
  PreencheDataSetProduto('Misso Shiro','kg','Mercado','Mercearia Fuji',22);
  PreencheDataSetProduto('Alho Descascado','kg','Hortifruti','Batata, o Rei do Alho',15.5);
  PreencheDataSetProduto('Capim Limão','kg','Hortifruti','Alcibiades G. Quintas',15);
  PreencheDataSetProduto('Abacate ','kg','Hortifruti','Alcibiades G. Quintas',6.8);
  PreencheDataSetProduto('Coca Cola (lata)','unid','Bebidas','Rio de Janeiro',2.90333333333333);
  PreencheDataSetProduto('Coca Cola Zero (lata)','unid','Bebidas','Rio de Janeiro',2.89);
  PreencheDataSetProduto('Schweppes Citrus','unid','Bebidas','Rio de Janeiro',2.8925);
  PreencheDataSetProduto('Margarina Qualy 500 g','kg','Mercado','Top Alto',8.64);
  PreencheDataSetProduto('Beterraba','kg','Hortifruti','Umehara',1.47);
  PreencheDataSetProduto('Banana da Terra','kg','Hortifruti','Cheiro Verde',1.48);
  PreencheDataSetProduto('Pescados - Namorado Fresco Sushi','kg','Sushi','DM Com. Pescados',22.9);
  PreencheDataSetProduto('Sal Sushi','kg','Sushi','J. Araujo (Arcofood)',0.8);
  PreencheDataSetProduto('Ovos Extra Sushi','unid','Sushi','Umehara',0.280555555555556);
  PreencheDataSetProduto('Pepino Japonês Sushi','kg','Sushi','Alcibiades G. Quintas',2.35849056603774);
  PreencheDataSetProduto('Aveia Quaker Flocos cx 200g','unid','Mercado','Mercadinho Bambina',3.3);
  PreencheDataSetProduto('Creme de Leite Chantily','kg','Mercado','Mercadinho Bambina',35);
  PreencheDataSetProduto('Mamão Papaya','kg','Hortifruti','Feira',3.08641975308642);
  PreencheDataSetProduto('Jiló','kg','Hortifruti','Alcibiades G. Quintas',5);
  PreencheDataSetProduto('Funcho','kg','Hortifruti','Alcibiades G. Quintas',10);
  PreencheDataSetProduto('Pimenta Dedo de Moça','kg','Hortifruti','Alcibiades G. Quintas',20);
  PreencheDataSetProduto('Pimenta de Cheiro','kg','Hortifruti','Alcibiades G. Quintas',25);
  PreencheDataSetProduto('Pimenta Biquinho','kg','Hortifruti','Alcibiades G. Quintas',50);
  PreencheDataSetProduto('Pimenta Malagueta','kg','Hortifruti','Alcibiades G. Quintas',60);
  PreencheDataSetProduto('Agrião','kg','Hortifruti','Umehara',3.25);
  PreencheDataSetProduto('Batata Palito 9M','kg','Mercado','Marfrig',6.0204);
  PreencheDataSetProduto('Aves - Galeto','kg','Carnes','Reginaves',8.4);
  PreencheDataSetProduto('Aves - Filé de Coxa','kg','Carnes','Reginaves',8.7);
  PreencheDataSetProduto('Etiqueta Pimaco','cx','Escritório','Papelex',55.54);
  PreencheDataSetProduto('Papel Chamex A4 Office','pcte','Escritório','Papelex',17.5);
  PreencheDataSetProduto('Grampo 26/6','cx','Escritório','Papelex',4.51);
  PreencheDataSetProduto('Fita Durex 12x30','unid','Escritório','Papelex',0.66);
  PreencheDataSetProduto('Lápis','unid','Escritório','Papelex',0.67);
  PreencheDataSetProduto('Cartão Ponto Mensal','pcte','Escritório','Papelex',11.5);
  PreencheDataSetProduto('Toner HP Preto','unid','Escritório','Papelex',392.87);
  PreencheDataSetProduto('Bloco Mov. Caixa Saída/ Entrada','unid','Escritório','Papelex',1.21);
  PreencheDataSetProduto('Mate Orgânico Limão','unid','Bebidas','Ceni',4.76081);
  PreencheDataSetProduto('Mate Orgânico Natural','unid','Bebidas','Ceni',4.76081);
  PreencheDataSetProduto('Alecrim','kg','Hortifruti','Umehara',18.5);
  PreencheDataSetProduto('Rúcula','kg','Hortifruti','Umehara',4.9);
  PreencheDataSetProduto('Maxixe','kg','Hortifruti','Alcibiades G. Quintas',4);
  PreencheDataSetProduto('Tomate Molho','kg','Hortifruti','Alcibiades G. Quintas',3.41463414634146);
  PreencheDataSetProduto('Nabo Japonês','kg','Hortifruti','Alcibiades G. Quintas',7);
  PreencheDataSetProduto('Rabanete','kg','Hortifruti','Alcibiades G. Quintas',6.8);
  PreencheDataSetProduto('Cream Cheese Sushi','kg','Sushi','LKAP',24.5);
  PreencheDataSetProduto('Cogumelo Fatiado Bd 2 Kg','bd','Mercado','Truticultura da Serra',37);
  PreencheDataSetProduto('Antibacterial Detergentye p/ mãos Bb 5lt','bb','Limpeza','Ecolab',147.84);
  PreencheDataSetProduto('AFVT - Antimicrobial Bb 10,4 KG ','bb','Limpeza','Ecolab',789.87);
  PreencheDataSetProduto('Solid Power (Lava Louça) 4 Kg','bb','Limpeza','Ecolab',529075);
  PreencheDataSetProduto('Ammoniated Glas Cln (Limpa vidro) BB 5L','bb','Limpeza','Ecolab',469925);
  PreencheDataSetProduto('Greasestrip Plus Bb 5 L','bb','Limpeza','Ecolab',265.74);
  PreencheDataSetProduto('Vercom Detergente Bb 5 Lt','bb','Limpeza','Ecolab',117365);
  PreencheDataSetProduto('Gergelim Branco Sushi','kg','Sushi','Mamy',16.85);
  PreencheDataSetProduto('Gergelim Preto','kg','Mercado','Mamy',30.59);
  PreencheDataSetProduto('Macarrão de Feijão (Harusame) 200g','pcte','Mercado','Mamy',8.48);
  PreencheDataSetProduto('Farinha de Rosca','kg','Mercado','Rioaves',9);
  PreencheDataSetProduto('Azeitona Verde Fatiada Bd 2 kg','bd','Mercado','J. Araujo (Arcofood)',22.49);
  PreencheDataSetProduto('Lentilha','kg','Mercado','Zamboni',12.72);
  PreencheDataSetProduto('Shoyu Premium (Mesa) Bb 5 Lt','bb','Mercado','Zamboni',53.42);
  PreencheDataSetProduto('Shoyu Tradicional (Cozinha) Bb 5 Lt','bb','Mercado','Zamboni',45.17);
  PreencheDataSetProduto('Palmito lata 500gr','unid','Mercado','Estrela Real',17.6666666666667);
  PreencheDataSetProduto('Maisena Amido de Milho 1 Kg','kg','Mercado','Rio Quality',10.8);
  PreencheDataSetProduto('Queijo Provolone Curado','kg','Mercado','Laticinios Alhambra',40.7);
  PreencheDataSetProduto('Amendoa Fatiada','kg','Mercado','Nova Geração (Casa Pedro)',70.6445);
  PreencheDataSetProduto('Castanha de Caju Crua','kg','Mercado','Nova Geração (Casa Pedro)',79.3787);
  PreencheDataSetProduto('Funghi Seco','kg','Mercado','Nova Geração (Casa Pedro)',79.8228);
  PreencheDataSetProduto('Manteiga de Garrafa','unid','Mercado','Nova Geração (Casa Pedro)',22.05);
  PreencheDataSetProduto('Vinagrete de Ervas','kg','Mercado','Nova Geração (Casa Pedro)',43.2016);
  PreencheDataSetProduto('Bombom Trufado','unid','Vendas Caixa','Chez Bonbon',1.6625);
  PreencheDataSetProduto('Tablet Diet','unid','Vendas Caixa','Chez Bonbon',2.1375);
  PreencheDataSetProduto('Casquinha de Laranja com chocolate','unid','Vendas Caixa','Chez Bonbon',6175);
  PreencheDataSetProduto('Aguardente 51','unid','Bebidas','Top Alto',7.68);
  PreencheDataSetProduto('Vodka Smirnoff','unid','Bebidas','Top Alto',30.99);
  PreencheDataSetProduto('Repolho','kg','Hortifruti','Umehara',1.21);
  PreencheDataSetProduto('Queijo Mozzarela Italiana pcte 880 gr','kg','Mercado','Agropart',41.7272727272727);
  PreencheDataSetProduto('Torta Capuccino Diet','fatia','Sobremesa','M2HP',5891);
  PreencheDataSetProduto('Torta Mousse de Chocolate ','fatia','Sobremesa','M2HP',4.13833333333333);
  PreencheDataSetProduto('Torta Brownie com Nozes','unid','Sobremesa','Nossos Sabores',5.9125);
  PreencheDataSetProduto('Torta Alemã','fatia','Sobremesa','Atelier dos Sabores',5.56916666666667);
  PreencheDataSetProduto('Quindão com Damasco','fatia','Sobremesa','Atelier dos Sabores',5.56833333333333);
  PreencheDataSetProduto('Torta Bem Casado de Doce de Leite','fatia','Sobremesa','Atelier dos Sabores',5.74583333333333);
  PreencheDataSetProduto('Torta Banana Crock','fatia','Sobremesa','Atelier dos Sabores',5.74583333333333);
  PreencheDataSetProduto('Torta de Cenoura c/ Chocolate','fatia','Sobremesa','Atelier dos Sabores',5.71083333333333);
  PreencheDataSetProduto('Amendoim Torrado','kg','Mercado','Tempero Carioca',15.5);
  PreencheDataSetProduto('Damasco Seco','kg','Mercado','Tempero Carioca',22.9);
  PreencheDataSetProduto('Biscoito de Milho Café ','kg','Mercado','Ind. Caseira de Doces Helena',22.1946428571429);
  PreencheDataSetProduto('Biscoito de Milho Venda ','kg','Vendas Caixa','Ind. Caseira de Doces Helena',22.1946428571429);
  PreencheDataSetProduto('Tangerina','kg','Hortifruti','Umehara',3.7);
  PreencheDataSetProduto('Ervilha Torta','kg','Hortifruti','Mercadinho Bambina',6.98);
  PreencheDataSetProduto('Pescados - Olho de Cão Sushi','kg','Sushi','Satiro',15);
  PreencheDataSetProduto('Cerveja Bohemia 600 ml','unid','Bebidas','CRBS',4.80708333333333);
  PreencheDataSetProduto('Carne Bovina - Perinha da Chã','kg','Carnes','Frisa',13.8);
  PreencheDataSetProduto('Pescados - Filé Linguado Cong. M','kg','Carnes','Pescarimarcar',29);
  PreencheDataSetProduto('Queijo Gorgonzola','kg','Mercado','Laticinios Alhambra',47.5);
  PreencheDataSetProduto('Repolho Roxo','kg','Hortifruti','Alcibiades G. Quintas',4);
  PreencheDataSetProduto('Cerveja Heineken Long Neck 330 ml','unid','Bebidas','Rio de Janeiro',4);
  PreencheDataSetProduto('Carne Bovina - Coração Alcatra','kg','Carnes','Marfrig',18.6633);
  PreencheDataSetProduto('Favas','kg','Mercado','Bonduelle',14.996875);
  PreencheDataSetProduto('Fundo de Alcachofra','kg','Hortifruti','Bonduelle',22.340625);
  PreencheDataSetProduto('Ervilha congelada','kg','Mercado','Bonduelle',9195);
  PreencheDataSetProduto('Salame Italiano','kg','Mercado','Mercadinho Bambina',59.98);
  PreencheDataSetProduto('Suco de Maracujá','unid','Mercado','Mercadinho Bambina',8.75);
  PreencheDataSetProduto('Presunto Cozido','kg','Carnes','Top Alto',13.9102941176471);
  PreencheDataSetProduto('Pescados - Kani','kg','Carnes','Peixaria Só Peixe',21.99);
  PreencheDataSetProduto('Pescados - Kani Sushi','kg','Sushi','Peixaria Só Peixe',21.99);
  PreencheDataSetProduto('Batata Inglesa','kg','Hortifruti','Alcibiades G. Quintas',1.8);
  PreencheDataSetProduto('Aspargos Frescos','kg','Hortifruti','Umehara',32);
  PreencheDataSetProduto('Salsa Crespa Sushi','kg','Sushi','Umehara',17.5);
  PreencheDataSetProduto('Cebolinha Verde Sushi','kg','Sushi','Umehara',7.5);
  PreencheDataSetProduto('Açucar Refinado Sushi','kg','Sushi','Rio Quality',2.25);
  PreencheDataSetProduto('Etiqueta Toledo 40 X 40','unid','Descartável','Suprimix',8);
  PreencheDataSetProduto('Café em Grão ','kg','Mercado','Café Fazenta (Orfeu)',9);
  PreencheDataSetProduto('Milho Mini Conserva lata 1,5 Kg','unid','Mercado','J. Araujo (Arcofood)',28);
  PreencheDataSetProduto('Milho Verde 2 Kg','unid','Mercado','Zamboni',7.87);
  PreencheDataSetProduto('Vinagre de Vinho Tinto 750 ml','unid','Mercado','CDI',2.74833333333333);
  PreencheDataSetProduto('Quiabo','kg','Hortifruti','Umehara',5.75868372943327);
  PreencheDataSetProduto('Uva s/ Caroço','kg','Hortifruti','Umehara',11.8);
  PreencheDataSetProduto('Pescados - Carne de siri','kg','Carnes','Peixaria Só Peixe',22.9);
  PreencheDataSetProduto('Azeite Deleyda 500 ml','unid','Mercado','Casa Flora',23.8158333333333);
  PreencheDataSetProduto('Chocolate em Pó Solúvel 200g','unid','Mercado','Mercadinho Bambina',13.5);
  PreencheDataSetProduto('Chá verde 200gr','pcte','Mercado','Damy',13.92);
  PreencheDataSetProduto('Óleo de Gergelim','unid','Mercado','Damy',54);
  PreencheDataSetProduto('Flocos de Arroz (cozinha)','kg','Mercado','Nova Geração (Casa Pedro)',17.82);
  PreencheDataSetProduto('Cuscus','kg','Mercado','Tempero Carioca',26.5);
  PreencheDataSetProduto('Mostarda Dijom em Grão','unid','Mercado','Tempero Carioca',21.9);
  PreencheDataSetProduto('Pescados - Atum Fresco','kg','Carnes','Toca da Lagosta',15);
  PreencheDataSetProduto('Pescados - Dourado Fresco Sushi','kg','Sushi','Toca da Lagosta',19);
  PreencheDataSetProduto('Sacola Camiseta Branca Doce','unid','Descartável','Ding Show',0.0173333333333333);
  PreencheDataSetProduto('Sacola Camiseta Branca Sobremesa','unid','Descartável','Ding Show',26);
  PreencheDataSetProduto('Torta Mousse de Chocolate Diet','fatia','Sobremesa','M2HP',4.90916666666667);
  PreencheDataSetProduto('Xarope de Groselha','unid','Mercado','Rio Quality',4.85);
  PreencheDataSetProduto('Queijo Prato','kg','Mercado','Laticinios Alhambra',26);
  PreencheDataSetProduto('Bandeja Alumínio 3 Div. Cx 100','unid','Descartável','Italimp',621);
  PreencheDataSetProduto('Torta Financier com Quindim','fatia','Sobremesa','Atelier dos Sabores',5.92416666666667);
  PreencheDataSetProduto('Vinho  Espumante Veuve Du Vernay 187 ml','unid','Bebidas','Casa Flora',14.08);
  PreencheDataSetProduto('Vinho Alfredo Roca Malbec 375 ml','unid','Bebidas','Casa Flora',23.6583333333333);
  PreencheDataSetProduto('Vinho Benjamin Chardonnay 750 ml','unid','Bebidas','Casa Flora',25565);
  PreencheDataSetProduto('Vinho Benjamin Malbec 375 ml','unid','Bebidas','Casa Flora',15.6375);
  PreencheDataSetProduto('Vinho Nieto Senet D.O.C. Malbec 750 ml','unid','Bebidas','Casa Flora',52.0466666666667);
  PreencheDataSetProduto('Vinho Cefiro Cab. Sauvignon 375 ml','unid','Bebidas','Casa Flora',26.9066666666667);
  PreencheDataSetProduto('Vinho Cefiro Sauv. Blanc 750 ml','unid','Bebidas','Casa Flora',44.5425);
  PreencheDataSetProduto('Vinho Sta Carolina Estrellas Cab. Sauv. 187ml','unid','Bebidas','Casa Flora',12.7479166666667);
  PreencheDataSetProduto('Copo de Sobremesa Cristal 180 ml','unid','Descartável','Rio Pak',0.3069);
  PreencheDataSetProduto('Cerveja Malzbier Brahma Long Neck','unid','Bebidas','CRBS',3.10916666666667);
  PreencheDataSetProduto('Água Tonica Diet','unid','Bebidas','CRBS',1.86083333333333);
  PreencheDataSetProduto('Ice Tea Pêssego','unid','Bebidas','CRBS',2.0125);
  PreencheDataSetProduto('Vagem Francesa','kg','Hortifruti','Umehara',9.5);
  PreencheDataSetProduto('Suíno - Barriga Suína','kg','Carnes','Aurora',10.17);
  PreencheDataSetProduto('Carne Bovina - Patinho','kg','Carnes','Frisa',14.6);
  PreencheDataSetProduto('Bobina Picotada 30X40','unid','Descartável','Sanda',11.94);
  PreencheDataSetProduto('Pano Multiuso Cross Hatch Laranja 300 M','unid','Descartável','Sanda',212.4);
  PreencheDataSetProduto('Saco de Lixo 300 Lt','pcte','Limpeza','Sanda',123.98);
  PreencheDataSetProduto('Bandeja Alumínio 220 ml cx 200 (Bolo)','unid','Descartável','Sanda',0.1981);
  PreencheDataSetProduto('Tortinha Arosa  81 unid','pcte','Mercado','Horn (Arosa)',31);
  PreencheDataSetProduto('Tortinha Arosa  64 unid','pcte','Mercado','Horn (Arosa)',34);
  PreencheDataSetProduto('Tortinha Arosa  72 unid','pcte','Mercado','Horn (Arosa)',34);
  PreencheDataSetProduto('Maracujá','kg','Hortifruti','Alcibiades G. Quintas',7.8);
  PreencheDataSetProduto('Feijão Fradinho','kg','Mercado','Top Alto',5098);
  PreencheDataSetProduto('Carne Bovina - Maminha','kg','Carnes','Top Alto',19.85);
  PreencheDataSetProduto('Suíno - Bacon Fatiado','kg','Carnes','Aurora',27.14);
  PreencheDataSetProduto('Girassol s/ Casca','kg','Mercado','Nova Geração (Casa Pedro)',16738);
  PreencheDataSetProduto('Abacaxi Cristalizado','kg','Mercado','Nova Geração (Casa Pedro)',32.9245);
  PreencheDataSetProduto('Kiwi Desidratado','kg','Mercado','Nova Geração (Casa Pedro)',44.9);
  PreencheDataSetProduto('Maçã Desidratada','kg','Mercado','Nova Geração (Casa Pedro)',48.9474);
  PreencheDataSetProduto('Pera Seca','kg','Mercado','Nova Geração (Casa Pedro)',53.0189);
  PreencheDataSetProduto('Queijo Mascarpone Ecila Bd 3,6 Kg','bd','Mercado','Laticinios Alhambra',84.8);
  PreencheDataSetProduto('Tomate Seco Conserva Bd 3 Kg','bd','Mercado','Laticinios Alhambra',78.1);
  PreencheDataSetProduto('Aves - Coração de Frango','kg','Carnes','Nutry Max',11.39);
  PreencheDataSetProduto('Zix 40','bb','Limpeza','Ecolab',147);
  PreencheDataSetProduto('Papel Higiênico (P.H. Interf.) Cx 60','unid','Descartável','Melhoramentos',2.23633333333333);
  PreencheDataSetProduto('Oásis enforce (limpador clorado) Bb5lt','bb','Limpeza','Ecolab',350.25);
  PreencheDataSetProduto('Silver Power Talher','bb','Limpeza','Ecolab',426.85);
  PreencheDataSetProduto('Bandeja 3 Div. Delivery Cx 150','unid','Descartável','FNS',2.15757777777778);
  PreencheDataSetProduto('Suíno - Linguiça Fina Defumada','kg','Carnes','Top Alto',10.65);
  PreencheDataSetProduto('Molho Ostra','unid','Mercado','Mamy',13.5);
  PreencheDataSetProduto('Pescados - Camarão Seco','kg','Carnes','Cambuci',110);
  PreencheDataSetProduto('Catchup 3,6 Kg','bb','Mercado','Rio Quality',14.5);
  PreencheDataSetProduto('Arroz Japonês (sushi)','kg','Sushi','Wah Sin',5.66666666666667);
  PreencheDataSetProduto('Wasabi em Pó','kg','Sushi','Wah Sin',35);
  PreencheDataSetProduto('Chocolate Granulado 1,01 Kg','kg','Mercado','CDI',9.44);
  PreencheDataSetProduto('Sukita Laranja Pet 2 Lt','unid','Bebidas','Rio de Janeiro',9.45);
  PreencheDataSetProduto('Pescados - Olhete Fresco Sushi','kg','Sushi','Toca da Lagosta',19.9);
  PreencheDataSetProduto('Massa para Lasanha','kg','Mercado','Fabene',9.9);
  PreencheDataSetProduto('Louro','kg','Hortifruti','Umehara',20);
  PreencheDataSetProduto('Gengibre','kg','Hortifruti','Alcibiades G. Quintas',6.7911714770798);
  PreencheDataSetProduto('Alface Americana    ','kg','Hortifruti','Umehara',1.63612565445026);
  PreencheDataSetProduto('Shitake Sushi','kg','Sushi','Mercearia Fuji',140);
  PreencheDataSetProduto('Pimenta Japonesa (Kimuchi)','unid','Sushi','Mercearia Fuji',30);
  PreencheDataSetProduto('Sweet Chilli Sauce 650 ml','unid','Sushi','Mercearia Fuji',30);
  PreencheDataSetProduto('Ameixa sem Caroço','kg','Mercado','Tempero Carioca',15.9);
  PreencheDataSetProduto('Pimenta Calabresa','kg','Mercado','Tempero Carioca',18);
  PreencheDataSetProduto('Maçã Ácida','kg','Hortifruti','Cheiro Verde',7.3);
  PreencheDataSetProduto('Aneto','kg','Hortifruti','Alcibiades G. Quintas',30);
  PreencheDataSetProduto('Goma de Tapioca','kg','Mercado','Feira',8);
  PreencheDataSetProduto('Suíno - Filezinho Suíno','kg','Carnes','Top Alto',9.98);
  PreencheDataSetProduto('Perfumador de Ambiente','unid','Limpeza','Celpa Quimica',60);
  PreencheDataSetProduto('Farinha Panco (sushi)','kg','Sushi','mamy',17.7);
  PreencheDataSetProduto('Farinha de Trigo (sushi)','kg','Sushi','CDI',1622);
  PreencheDataSetProduto('Massa de Harumaki (sushi)','folha','Sushi','mamy',0.575833333333333);
  PreencheDataSetProduto('Marca Texto Pilot','unid','Escritório','Papelex',1.93);
  PreencheDataSetProduto('Pasta L','unid','Escritório','Papelex',0.75);
  PreencheDataSetProduto('Folha de Alga 50F (cozinha)','pcte','Mercado','Wah Sin',33);
  PreencheDataSetProduto('Banete Pec Pão (cozinha)','kg','Mercado','Super Mercado Zonasul',19.8774509803922);
end;

end.
